name: brand1_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animate_do: ^3.3.1
  base_project:
    path: ../base_project
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0

dependency_overrides:
  config:
    path: config

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Bold.ttf
        - asset: fonts/Oswald-ExtraLight.ttf
        - asset: fonts/Oswald-Light.ttf
        - asset: fonts/Oswald-Medium.ttf
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-SemiBold.ttf
